lib/ebaze_web/router.ex
defmodule EbazeWeb.Router do
  use EbazeWeb, :router

  pipeline :auth do
    plug Ebaze.Accounts.Pipeline
  end

  pipeline :ensure_auth do
    plug Guardian.Plug.EnsureAuthenticated
  end

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", EbazeWeb do
    pipe_through [:browser, :auth]

    get "/", PageController, :index

    resources "/signup", UserController, only: [:new, :create]

    resources "/auctions", AuctionController, only: [:index]

    resources "/sign-in", SessionController, only: [:new, :create]

    post "/signout", SessionController, :signout
  end

  scope "/", EbazeWeb do
    pipe_through [:browser, :auth, :ensure_auth]

    resources "/users", UserController, except: [:new, :create]

    resources "/auctions", AuctionController, except: [:index]

    get "/my-auctions", AuctionController, :my_auctions

    get "/protected", PageController, :protected
  end
end

lib/ebaze_web/views/layout_view.ex
defmodule EbazeWeb.LayoutView do
  use EbazeWeb, :view
end

lib/ebaze_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Ebaze</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <%= if Ebaze.Accounts.Guardian.Plug.authenticated?(@conn) do %>
            <ul>
              <%= link "New Listing", to: Routes.auction_path(@conn, :new), class: "nav-link" %>
              <%= link "My Listings", to: Routes.auction_path(@conn, :my_auctions), class: "nav-link" %>
              <%= link "Signout", to: Routes.session_path(@conn, :signout), method: :post, class: "nav-link" %>
            </ul>
          <% else %>
            <ul>
              <div>
                <%= link "Signup", to: Routes.user_path(@conn, :new), class: "nav-link", class: "button" %>    
              </div>
              <div>
                <%= link "Sign in", to: Routes.session_path(@conn, :new), class: "nav-link", class: "button" %>    
              </div>
            </ul>
          <% end %>      
        </nav>
        <a href="/" class="ebaze-logo">
          <img src="<%= Routes.static_path(@conn, "/images/logo.png") %>" alt="Ebaze Logo"/>
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>